<?php

/**
 * IssuedDocumentTotalsTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  FattureInCloud
 * @author   Fatture In Cloud API team
 * @link     https://fattureincloud.it
 */

/**
 * Fatture in Cloud API v2 - API Reference
 *
 * ## Request informations In every request description you will be able to find some additional informations about context, permissions and supported functionality:  | Parameter | Description | |-----------|-------------| | 👥 Context | Indicate the subject of the request. Can be `company`, `user` or `accountant`.  | | 🔒 Required scope | If present, indicates the required scope to fulfill the request. | | 🔍 Filtering | If present, indicates which fields support the filtering feature. | | ↕️ Sorting | If present, indicates which fields support the sorting feature. | | 📄 Paginated results | If present, indicate that the results are paginated. | | 🎩 Customized responses supported | If present, indicate that you can use `field` or `fieldset` to customize the response body. |  For example the request `GET /entities/{entityRole}` have tis informations: \\ 👥 Company context \\ 🔒 Required scope: `entity.clients:r` or `entity.suppliers:r` (depending on `entityRole`) \\ 🔍 Filtering: `id`, `name` \\ ↕️ Sorting: `id`, `name` \\ 📄 Paginated results \\ 🎩 Customized responses supported  Keep in mind that if you are making **company realted requests**, you will need to specify the company id in the requests: ``` GET /c/{company_id}/issued_documents ```
 *
 * The version of the OpenAPI document: 2.0.6
 * Contact: info@fattureincloud.it
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FattureInCloud\Test\Model;

use PHPUnit\Framework\TestCase;
use \FattureInCloud\ObjectSerializer;

/**
 * IssuedDocumentTotalsTest Class Doc Comment
 *
 * @category    Class
 * @description IssuedDocumentTotals
 * @package     FattureInCloud
 * @author   Fatture In Cloud API team
 * @link     https://fattureincloud.it
 */
class IssuedDocumentTotalsTest extends TestCase
{
    public $array = [];
    public $object;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
        $json = '{
            "amount_net": 68.18,
            "taxable_amount": 68.18,
            "amount_vat": 6.82,
            "amount_gross": 75,
            "amount_due": 75,
            "payments_sum": 75,
            "amount_rivalsa": 10,
            "amount_net_with_rivalsa": 10,
            "amount_cassa": 10,
            "not_taxable_amount": 10,
            "taxable_amount_withholding_tax": 10,
            "amount_withholding_tax": 10,
            "taxable_amount_other_withholding_tax": 10,
            "amount_other_withholding_tax": 10,
            "stamp_duty": 10,
            "is_enasarco_maximal_exceeded": false,
            "payments_sum": 2,
            "vat_list": {
                "vat_item": {
                  "amount_net": 68.18,
                  "amount_vat": 6.82
                }
            }
        }';

        $this->array = json_decode($json, true);

        $this->object = ObjectSerializer::deserialize($json, '\FattureInCloud\Model\IssuedDocumentTotals');
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "IssuedDocumentTotals"
     */
    public function testIssuedDocumentTotals()
    {
        $this->assertInstanceOf('\FattureInCloud\Model\IssuedDocumentTotals', $this->object);
    }

    /**
     * Test attribute "amount_net"
     */
    public function testPropertyAmountNet()
    {
        $this->assertEquals($this->array['amount_net'], $this->object->getAmountNet());
    }

    /**
     * Test attribute "amount_rivalsa"
     */
    public function testPropertyAmountRivalsa()
    {
        $this->assertEquals($this->array['amount_rivalsa'], $this->object->getAmountRivalsa());
    }

    /**
     * Test attribute "amount_net_with_rivalsa"
     */
    public function testPropertyAmountNetWithRivalsa()
    {
        $this->assertEquals($this->array['amount_net_with_rivalsa'], $this->object->getAmountNetWithRivalsa());
    }

    /**
     * Test attribute "amount_cassa"
     */
    public function testPropertyAmountCassa()
    {
        $this->assertEquals($this->array['amount_cassa'], $this->object->getAmountCassa());
    }

    /**
     * Test attribute "taxable_amount"
     */
    public function testPropertyTaxableAmount()
    {
        $this->assertEquals($this->array['taxable_amount'], $this->object->getTaxableAmount());
    }

    /**
     * Test attribute "not_taxable_amount"
     */
    public function testPropertyNotTaxableAmount()
    {
        $this->assertEquals($this->array['not_taxable_amount'], $this->object->getNotTaxableAmount());
    }

    /**
     * Test attribute "amount_vat"
     */
    public function testPropertyAmountVat()
    {
        $this->assertEquals($this->array['amount_vat'], $this->object->getAmountVat());
    }

    /**
     * Test attribute "amount_gross"
     */
    public function testPropertyAmountGross()
    {
        $this->assertEquals($this->array['amount_gross'], $this->object->getAmountGross());
    }

    /**
     * Test attribute "taxable_amount_withholding_tax"
     */
    public function testPropertyTaxableAmountWithholdingTax()
    {
        $this->assertEquals($this->array['taxable_amount_withholding_tax'], $this->object->getTaxableAmountWithholdingTax());
    }

    /**
     * Test attribute "amount_withholding_tax"
     */
    public function testPropertyAmountWithholdingTax()
    {
        $this->assertEquals($this->array['amount_withholding_tax'], $this->object->getAmountWithholdingTax());
    }

    /**
     * Test attribute "taxable_amount_other_withholding_tax"
     */
    public function testPropertyTaxableAmountOtherWithholdingTax()
    {
        $this->assertEquals($this->array['taxable_amount_other_withholding_tax'], $this->object->getTaxableAmountOtherWithholdingTax());
    }

    /**
     * Test attribute "amount_other_withholding_tax"
     */
    public function testPropertyAmountOtherWithholdingTax()
    {
        $this->assertEquals($this->array['amount_other_withholding_tax'], $this->object->getAmountOtherWithholdingTax());
    }

    /**
     * Test attribute "stamp_duty"
     */
    public function testPropertyStampDuty()
    {
        $this->assertEquals($this->array['stamp_duty'], $this->object->getStampDuty());
    }

    /**
     * Test attribute "amount_due"
     */
    public function testPropertyAmountDue()
    {
        $this->assertEquals($this->array['amount_due'], $this->object->getAmountDue());
    }

    /**
     * Test attribute "is_enasarco_maximal_exceeded"
     */
    public function testPropertyIsEnasarcoMaximalExceeded()
    {
        $this->assertEquals($this->array['is_enasarco_maximal_exceeded'], $this->object->getIsEnasarcoMaximalExceeded());
    }

    /**
     * Test attribute "payments_sum"
     */
    public function testPropertyPaymentsSum()
    {
        $this->assertEquals($this->array['payments_sum'], $this->object->getPaymentsSum());
    }

    /**
     * Test attribute "vat_list"
     */
    public function testPropertyVatList()
    {
        $vatList = $this->object->getVatList();
        $this->assertIsArray($vatList);
        if (!empty($vatList)) {
            $firstValue = reset($vatList);
            $this->assertInstanceOf(\FattureInCloud\Model\VatItem::class, $firstValue);
        }
    }
}
