<?php

/**
 * ListSuppliersResponseTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  FattureInCloud
 * @author   Fatture In Cloud API team
 * @link     https://fattureincloud.it
 */

/**
 * Fatture in Cloud API v2 - API Reference
 *
 * ## Request informations In every request description you will be able to find some additional informations about context, permissions and supported functionality:  | Parameter | Description | |-----------|-------------| | 👥 Context | Indicate the subject of the request. Can be `company`, `user` or `accountant`.  | | 🔒 Required scope | If present, indicates the required scope to fulfill the request. | | 🔍 Filtering | If present, indicates which fields support the filtering feature. | | ↕️ Sorting | If present, indicates which fields support the sorting feature. | | 📄 Paginated results | If present, indicate that the results are paginated. | | 🎩 Customized responses supported | If present, indicate that you can use `field` or `fieldset` to customize the response body. |  For example the request `GET /entities/{entityRole}` have tis informations: \\ 👥 Company context \\ 🔒 Required scope: `entity.clients:r` or `entity.suppliers:r` (depending on `entityRole`) \\ 🔍 Filtering: `id`, `name` \\ ↕️ Sorting: `id`, `name` \\ 📄 Paginated results \\ 🎩 Customized responses supported  Keep in mind that if you are making **company realted requests**, you will need to specify the company id in the requests: ``` GET /c/{company_id}/issued_documents ```
 *
 * The version of the OpenAPI document: 2.0.6
 * Contact: info@fattureincloud.it
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FattureInCloud\Test\Model;

use PHPUnit\Framework\TestCase;
use \FattureInCloud\ObjectSerializer;

/**
 * ListSuppliersResponseTest Class Doc Comment
 *
 * @category    Class
 * @description ListSuppliersResponse
 * @package     FattureInCloud
 * @author   Fatture In Cloud API team
 * @link     https://fattureincloud.it
 */
class ListSuppliersResponseTest extends TestCase
{
    public $array = [];
    public $object;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
        $json = '{
            "current_page": 2,
            "first_page_url": "page=1",
            "from": 1,
            "last_page": 3,
            "last_page_url": "page=3",
            "next_page_url": "page=3",
            "path": "/archive",
            "per_page": 50,
            "prev_page_url": "page=1",
            "to": 3,
            "total": 155,
            "data": [
                {
                  "id": 12345,
                  "code": "AE86",
                  "name": "Mario Rossi S.R.L.",
                  "type": "company",
                  "first_name": "Mario",
                  "last_name": "Rossi",
                  "contact_person": "",
                  "vat_number": "111222333",
                  "tax_code": "111122233",
                  "address_street": "Corso Magellano, 46",
                  "address_postal_code": "20146",
                  "address_city": "Milano",
                  "address_province": "MI",
                  "address_extra": "",
                  "country": "Italia",
                  "email": "mario.rossi@example.com",
                  "certified_email": "mario.rossi@pec.example.com",
                  "phone": "1234567890",
                  "fax": "123456789",
                  "notes": "",
                  "created_at": "2021-15-08",
                  "updated_at": "2021-15-08"
                },
                {
                  "id": 12346,
                  "code": "GT86",
                  "name": "Maria Grossi S.R.L.",
                  "type": "company",
                  "first_name": "",
                  "last_name": "",
                  "contact_person": "",
                  "vat_number": "200020102020",
                  "tax_code": "200020102020",
                  "address_street": "Vicolo stretto, 32",
                  "address_postal_code": "20146",
                  "address_city": "Milano",
                  "address_province": "MI",
                  "address_extra": "",
                  "country": "Italia",
                  "email": "maria.grossi@example.com",
                  "certified_email": "maria.grossi@pec.example.com",
                  "phone": "0987654321",
                  "fax": "098765432",
                  "notes": "",
                  "created_at": "2021-15-09",
                  "updated_at": "2021-15-09"
                }
            ]
        }';

        $this->array = json_decode($json, true);

        $this->object = ObjectSerializer::deserialize($json, '\FattureInCloud\Model\ListSuppliersResponse');
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ListSuppliersResponse"
     */
    public function testListSuppliersResponse()
    {
        $this->assertInstanceOf(\FattureInCloud\Model\ListSuppliersResponse::class, $this->object);
    }

    /**
     * Test attribute "current_page"
     */
    public function testPropertyCurrentPage()
    {
        $this->assertEquals($this->array['current_page'], $this->object->getCurrentPage());
    }

    /**
     * Test attribute "first_page_url"
     */
    public function testPropertyFirstPageUrl()
    {
        $this->assertEquals($this->array['first_page_url'], $this->object->getFirstPageUrl());
    }

    /**
     * Test attribute "from"
     */
    public function testPropertyFrom()
    {
        $this->assertEquals($this->array['from'], $this->object->getFrom());
    }

    /**
     * Test attribute "last_page"
     */
    public function testPropertyLastPage()
    {
        $this->assertEquals($this->array['last_page'], $this->object->getLastPage());
    }

    /**
     * Test attribute "last_page_url"
     */
    public function testPropertyLastPageUrl()
    {
        $this->assertEquals($this->array['last_page_url'], $this->object->getLastPageUrl());
    }

    /**
     * Test attribute "next_page_url"
     */
    public function testPropertyNextPageUrl()
    {
        $this->assertEquals($this->array['next_page_url'], $this->object->getNextPageUrl());
    }

    /**
     * Test attribute "path"
     */
    public function testPropertyPath()
    {
        $this->assertEquals($this->array['path'], $this->object->getPath());
    }

    /**
     * Test attribute "per_page"
     */
    public function testPropertyPerPage()
    {
        $this->assertEquals($this->array['per_page'], $this->object->getPerPage());
    }

    /**
     * Test attribute "prev_page_url"
     */
    public function testPropertyPrevPageUrl()
    {
        $this->assertEquals($this->array['prev_page_url'], $this->object->getPrevPageUrl());
    }

    /**
     * Test attribute "to"
     */
    public function testPropertyTo()
    {
        $this->assertEquals($this->array['to'], $this->object->getTo());
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
        $this->assertEquals($this->array['total'], $this->object->getTotal());
    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {
        $this->assertIsArray($this->object->getData());
    }
}
