<?php

/**
 * PaymentMethodTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  FattureInCloud
 * @author   Fatture In Cloud API team
 * @link     https://fattureincloud.it
 */

/**
 * Fatture in Cloud API v2 - API Reference
 *
 * ## Request informations In every request description you will be able to find some additional informations about context, permissions and supported functionality:  | Parameter | Description | |-----------|-------------| | 👥 Context | Indicate the subject of the request. Can be `company`, `user` or `accountant`.  | | 🔒 Required scope | If present, indicates the required scope to fulfill the request. | | 🔍 Filtering | If present, indicates which fields support the filtering feature. | | ↕️ Sorting | If present, indicates which fields support the sorting feature. | | 📄 Paginated results | If present, indicate that the results are paginated. | | 🎩 Customized responses supported | If present, indicate that you can use `field` or `fieldset` to customize the response body. |  For example the request `GET /entities/{entityRole}` have tis informations: \\ 👥 Company context \\ 🔒 Required scope: `entity.clients:r` or `entity.suppliers:r` (depending on `entityRole`) \\ 🔍 Filtering: `id`, `name` \\ ↕️ Sorting: `id`, `name` \\ 📄 Paginated results \\ 🎩 Customized responses supported  Keep in mind that if you are making **company realted requests**, you will need to specify the company id in the requests: ``` GET /c/{company_id}/issued_documents ```
 *
 * The version of the OpenAPI document: 2.0.6
 * Contact: info@fattureincloud.it
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FattureInCloud\Test\Model;

use PHPUnit\Framework\TestCase;
use \FattureInCloud\ObjectSerializer;

/**
 * PaymentMethodTest Class Doc Comment
 *
 * @category    Class
 * @description PaymentMethod
 * @package     FattureInCloud
 * @author   Fatture In Cloud API team
 * @link     https://fattureincloud.it
 */
class PaymentMethodTest extends TestCase
{
    public $array = [];
    public $object;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
        $json = '{  
            "id": 12346,
            "name": "Bonifico bancario",
            "type": "standard",
            "is_default": true,
            "details": [{
                "title":"t1"
            }],
            "default_payment_account": {
                "id": 21,
                "name": "n1"
            }
        }';

        $this->array = json_decode($json, true);

        $this->object = ObjectSerializer::deserialize($json, '\FattureInCloud\Model\PaymentMethod');
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PaymentMethod"
     */
    public function testPaymentMethod()
    {
        $this->assertInstanceOf(\FattureInCloud\Model\PaymentMethod::class, $this->object);
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        $this->assertEquals($this->array['id'], $this->object->getId());
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        $this->assertEquals($this->array['name'], $this->object->getName());
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
        $this->assertEquals($this->array['type'], $this->object->getType());
    }

    /**
     * Test attribute "is_default"
     */
    public function testPropertyIsDefault()
    {
        $this->assertEquals($this->array['is_default'], $this->object->getIsDefault());
    }

    /**
     * Test attribute "default_payment_account"
     */
    public function testPropertyDefaultPaymentAccount()
    {
        $this->assertInstanceOf(\FattureInCloud\Model\PaymentAccount::class, $this->object->getDefaultPaymentAccount());
    }

    /**
     * Test attribute "details"
     */
    public function testPropertyDetails()
    {
        $details = $this->object->getDetails();
        $this->assertIsArray($details);
        foreach ($details as $detail) {
            $this->assertInstanceOf(\FattureInCloud\Model\PaymentMethodDetails::class, $detail);
        }
    }

    /**
     * Test setter for "id"
     */
    public function testSetId()
    {
        $object = new \FattureInCloud\Model\PaymentMethod();
        $testValue = 12345;

        $object->setId($testValue);
        $this->assertEquals($testValue, $object->getId());
    }

    /**
     * Test setter for "name"
     */
    public function testSetName()
    {
        $object = new \FattureInCloud\Model\PaymentMethod();
        $testValue = 'Test Payment Method';

        $object->setName($testValue);
        $this->assertEquals($testValue, $object->getName());
    }

    /**
     * Test setter for "type"
     */
    public function testSetType()
    {
        $object = new \FattureInCloud\Model\PaymentMethod();
        $testValue = 'custom';

        $object->setType($testValue);
        $this->assertEquals($testValue, $object->getType());
    }

    /**
     * Test setter for "is_default"
     */
    public function testSetIsDefault()
    {
        $object = new \FattureInCloud\Model\PaymentMethod();
        $testValue = false;

        $object->setIsDefault($testValue);
        $this->assertEquals($testValue, $object->getIsDefault());
    }

    /**
     * Test setter for "default_payment_account"
     */
    public function testSetDefaultPaymentAccount()
    {
        $object = new \FattureInCloud\Model\PaymentMethod();
        $testValue = ['id' => 123, 'name' => 'Test Account'];

        $object->setDefaultPaymentAccount($testValue);
        $this->assertEquals($testValue, $object->getDefaultPaymentAccount());
    }

    /**
     * Test setter for "details"
     */
    public function testSetDetails()
    {
        $object = new \FattureInCloud\Model\PaymentMethod();
        $testValue = [['title' => 'Test Detail']];

        $object->setDetails($testValue);
        $this->assertEquals($testValue, $object->getDetails());
    }

    /**
     * Test setter for "bank_iban"
     */
    public function testSetBankIban()
    {
        $object = new \FattureInCloud\Model\PaymentMethod();
        $testValue = 'IT60X0542811101000000123456';

        $object->setBankIban($testValue);
        $this->assertEquals($testValue, $object->getBankIban());
    }

    /**
     * Test setter for "bank_name"
     */
    public function testSetBankName()
    {
        $object = new \FattureInCloud\Model\PaymentMethod();
        $testValue = 'Test Bank';

        $object->setBankName($testValue);
        $this->assertEquals($testValue, $object->getBankName());
    }

    /**
     * Test setter for "bank_beneficiary"
     */
    public function testSetBankBeneficiary()
    {
        $object = new \FattureInCloud\Model\PaymentMethod();
        $testValue = 'Test Beneficiary';

        $object->setBankBeneficiary($testValue);
        $this->assertEquals($testValue, $object->getBankBeneficiary());
    }

    /**
     * Test setter for "ei_payment_method"
     */
    public function testSetEiPaymentMethod()
    {
        $object = new \FattureInCloud\Model\PaymentMethod();
        $testValue = 'MP01';

        $object->setEiPaymentMethod($testValue);
        $this->assertEquals($testValue, $object->getEiPaymentMethod());
    }
}
