<?php

/**
 * PendingReceivedDocumentTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  FattureInCloud
 * @author   Fatture In Cloud API team
 * @link     https://fattureincloud.it
 */

/**
 * Fatture in Cloud API v2 - API Reference
 *
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.1.8
 * Contact: info@fattureincloud.it
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FattureInCloud\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PendingReceivedDocumentTest Class Doc Comment
 *
 * @category    Class
 * @description PendingReceivedDocument
 * @package     FattureInCloud
 * @author   Fatture In Cloud API team
 * @link     https://fattureincloud.it
 */
class PendingReceivedDocumentTest extends TestCase
{
    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PendingReceivedDocument"
     */
    public function testPendingReceivedDocument()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $this->assertInstanceOf(\FattureInCloud\Model\PendingReceivedDocument::class, $object);
        
        // Test that object can be created with valid data
        $object->setId(12345);
        $object->setDate('2024-04-17');
        $object->setSubject('Test Document');
        $object->setFilename('test.pdf');
        
        $this->assertEquals(12345, $object->getId());
        $this->assertEquals('2024-04-17', $object->getDate());
        $this->assertEquals('Test Document', $object->getSubject());
        $this->assertEquals('test.pdf', $object->getFilename());
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = 12345;
        
        $object->setId($testValue);
        $this->assertEquals($testValue, $object->getId());
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = '2024-04-17';
        
        $object->setDate($testValue);
        $this->assertEquals($testValue, $object->getDate());
    }

    /**
     * Test attribute "subject"
     */
    public function testPropertySubject()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = 'Test Document Subject';
        
        $object->setSubject($testValue);
        $this->assertEquals($testValue, $object->getSubject());
    }

    /**
     * Test attribute "filename"
     */
    public function testPropertyFilename()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = 'test-document.pdf';
        
        $object->setFilename($testValue);
        $this->assertEquals($testValue, $object->getFilename());
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = \FattureInCloud\Model\PendingReceivedDocumentType::MAIL;
        
        $object->setType($testValue);
        $this->assertEquals($testValue, $object->getType());
    }

    /**
     * Test attribute "attachment_url"
     */
    public function testPropertyAttachmentUrl()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = 'https://example.com/attachment.pdf';
        
        $object->setAttachmentUrl($testValue);
        $this->assertEquals($testValue, $object->getAttachmentUrl());
    }

    /**
     * Test attribute "amount_gross"
     */
    public function testPropertyAmountGross()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = 122.50;
        
        $object->setAmountGross($testValue);
        $this->assertEquals($testValue, $object->getAmountGross());
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = new \FattureInCloud\Model\Currency();
        
        $object->setCurrency($testValue);
        $this->assertEquals($testValue, $object->getCurrency());
    }

    /**
     * Test attribute "document_type"
     */
    public function testPropertyDocumentType()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = 'invoice';
        
        $object->setDocumentType($testValue);
        $this->assertEquals($testValue, $object->getDocumentType());
    }

    /**
     * Test attribute "supplier_name"
     */
    public function testPropertySupplierName()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = 'Test Supplier Name';
        
        $object->setSupplierName($testValue);
        $this->assertEquals($testValue, $object->getSupplierName());
    }

    /**
     * Test attribute "cost_center"
     */
    public function testPropertyCostCenter()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = 'Test Cost Center';
        
        $object->setCostCenter($testValue);
        $this->assertEquals($testValue, $object->getCostCenter());
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = 'Test Category';
        
        $object->setCategory($testValue);
        $this->assertEquals($testValue, $object->getCategory());
    }

    /**
     * Test attribute "other_attachments"
     */
    public function testPropertyOtherAttachments()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = [new \FattureInCloud\Model\Attachment()];
        
        $object->setOtherAttachments($testValue);
        $this->assertEquals($testValue, $object->getOtherAttachments());
    }

    /**
     * Test attribute "emssion_date"
     */
    public function testPropertyEmssionDate()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = '2024-04-15';
        
        $object->setEmssionDate($testValue);
        $this->assertEquals($testValue, $object->getEmssionDate());
    }

    /**
     * Test attribute "payments_list"
     */
    public function testPropertyPaymentsList()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = [new \FattureInCloud\Model\PendingReceivedDocumentPaymentsListItem()];
        
        $object->setPaymentsList($testValue);
        $this->assertEquals($testValue, $object->getPaymentsList());
    }

    /**
     * Test attribute "amount_net"
     */
    public function testPropertyAmountNet()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = 100.00;
        
        $object->setAmountNet($testValue);
        $this->assertEquals($testValue, $object->getAmountNet());
    }

    /**
     * Test attribute "amount_vat"
     */
    public function testPropertyAmountVat()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = 22.50;
        
        $object->setAmountVat($testValue);
        $this->assertEquals($testValue, $object->getAmountVat());
    }

    /**
     * Test attribute "import_error"
     */
    public function testPropertyImportError()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = 'Test import error message';
        
        $object->setImportError($testValue);
        $this->assertEquals($testValue, $object->getImportError());
    }

    /**
     * Test attribute "extracted_data"
     */
    public function testPropertyExtractedData()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = new \FattureInCloud\Model\PendingReceivedDocumentExtractedData();
        
        $object->setExtractedData($testValue);
        $this->assertEquals($testValue, $object->getExtractedData());
    }

    /**
     * Test setter for "id"
     */
    public function testSetId()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = 12345;
        
        $object->setId($testValue);
        $this->assertEquals($testValue, $object->getId());
    }

    /**
     * Test setter for "date"
     */
    public function testSetDate()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = '2024-04-17';
        
        $object->setDate($testValue);
        $this->assertEquals($testValue, $object->getDate());
    }

    /**
     * Test setter for "subject"
     */
    public function testSetSubject()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = 'Test Document Subject';
        
        $object->setSubject($testValue);
        $this->assertEquals($testValue, $object->getSubject());
    }

    /**
     * Test setter for "filename"
     */
    public function testSetFilename()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = 'test-document.pdf';
        
        $object->setFilename($testValue);
        $this->assertEquals($testValue, $object->getFilename());
    }

    /**
     * Test setter for "type"
     */
    public function testSetType()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = \FattureInCloud\Model\PendingReceivedDocumentType::MAIL;
        
        $object->setType($testValue);
        $this->assertEquals($testValue, $object->getType());
    }

    /**
     * Test setter for "attachment_url"
     */
    public function testSetAttachmentUrl()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = 'https://example.com/attachment.pdf';
        
        $object->setAttachmentUrl($testValue);
        $this->assertEquals($testValue, $object->getAttachmentUrl());
    }

    /**
     * Test setter for "amount_gross"
     */
    public function testSetAmountGross()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = 122.50;
        
        $object->setAmountGross($testValue);
        $this->assertEquals($testValue, $object->getAmountGross());
    }

    /**
     * Test setter for "currency"
     */
    public function testSetCurrency()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = new \FattureInCloud\Model\Currency();
        
        $object->setCurrency($testValue);
        $this->assertEquals($testValue, $object->getCurrency());
    }

    /**
     * Test setter for "document_type"
     */
    public function testSetDocumentType()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = 'invoice';
        
        $object->setDocumentType($testValue);
        $this->assertEquals($testValue, $object->getDocumentType());
    }

    /**
     * Test setter for "supplier_name"
     */
    public function testSetSupplierName()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = 'Test Supplier Name';
        
        $object->setSupplierName($testValue);
        $this->assertEquals($testValue, $object->getSupplierName());
    }

    /**
     * Test setter for "cost_center"
     */
    public function testSetCostCenter()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = 'Test Cost Center';
        
        $object->setCostCenter($testValue);
        $this->assertEquals($testValue, $object->getCostCenter());
    }

    /**
     * Test setter for "category"
     */
    public function testSetCategory()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = 'Test Category';
        
        $object->setCategory($testValue);
        $this->assertEquals($testValue, $object->getCategory());
    }

    /**
     * Test setter for "other_attachments"
     */
    public function testSetOtherAttachments()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = [new \FattureInCloud\Model\Attachment()];
        
        $object->setOtherAttachments($testValue);
        $this->assertEquals($testValue, $object->getOtherAttachments());
    }

    /**
     * Test setter for "emssion_date"
     */
    public function testSetEmssionDate()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = '2024-04-15';
        
        $object->setEmssionDate($testValue);
        $this->assertEquals($testValue, $object->getEmssionDate());
    }

    /**
     * Test setter for "payments_list"
     */
    public function testSetPaymentsList()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = [new \FattureInCloud\Model\PendingReceivedDocumentPaymentsListItem()];
        
        $object->setPaymentsList($testValue);
        $this->assertEquals($testValue, $object->getPaymentsList());
    }

    /**
     * Test setter for "amount_net"
     */
    public function testSetAmountNet()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = 100.00;
        
        $object->setAmountNet($testValue);
        $this->assertEquals($testValue, $object->getAmountNet());
    }

    /**
     * Test setter for "amount_vat"
     */
    public function testSetAmountVat()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = 22.50;
        
        $object->setAmountVat($testValue);
        $this->assertEquals($testValue, $object->getAmountVat());
    }

    /**
     * Test setter for "import_error"
     */
    public function testSetImportError()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = 'Test import error message';
        
        $object->setImportError($testValue);
        $this->assertEquals($testValue, $object->getImportError());
    }

    /**
     * Test setter for "extracted_data"
     */
    public function testSetExtractedData()
    {
        $object = new \FattureInCloud\Model\PendingReceivedDocument();
        $testValue = new \FattureInCloud\Model\PendingReceivedDocumentExtractedData();
        
        $object->setExtractedData($testValue);
        $this->assertEquals($testValue, $object->getExtractedData());
    }
}
