<?php

/**
 * ReceivedDocumentInfoTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  FattureInCloud
 * @author   Fatture In Cloud API team
 * @link     https://fattureincloud.it
 */

/**
 * Fatture in Cloud API v2 - API Reference
 *
 * ## Request informations In every request description you will be able to find some additional informations about context, permissions and supported functionality:  | Parameter | Description | |-----------|-------------| | 👥 Context | Indicate the subject of the request. Can be `company`, `user` or `accountant`.  | | 🔒 Required scope | If present, indicates the required scope to fulfill the request. | | 🔍 Filtering | If present, indicates which fields support the filtering feature. | | ↕️ Sorting | If present, indicates which fields support the sorting feature. | | 📄 Paginated results | If present, indicate that the results are paginated. | | 🎩 Customized responses supported | If present, indicate that you can use `field` or `fieldset` to customize the response body. |  For example the request `GET /entities/{entityRole}` have tis informations: \\ 👥 Company context \\ 🔒 Required scope: `entity.clients:r` or `entity.suppliers:r` (depending on `entityRole`) \\ 🔍 Filtering: `id`, `name` \\ ↕️ Sorting: `id`, `name` \\ 📄 Paginated results \\ 🎩 Customized responses supported  Keep in mind that if you are making **company realted requests**, you will need to specify the company id in the requests: ``` GET /c/{company_id}/issued_documents ```
 *
 * The version of the OpenAPI document: 2.0.6
 * Contact: info@fattureincloud.it
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FattureInCloud\Test\Model;

use PHPUnit\Framework\TestCase;
use \FattureInCloud\ObjectSerializer;

/**
 * ReceivedDocumentInfoTest Class Doc Comment
 *
 * @category    Class
 * @description
 * @package     FattureInCloud
 * @author   Fatture In Cloud API team
 * @link     https://fattureincloud.it
 */
class ReceivedDocumentInfoTest extends TestCase
{
    public $array = [];
    public $object;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
        $json = '{
            "default_values": {
                "detailed": false
            },
            "items_default_values": {
                "vat": 21
            },
            "countries_list": [
                "Italia",
                "Afghanistan",
                "Albania"
            ],
            "currencies_list": [
                {
                  "id": "AED",
                  "symbol": "AED",
                  "html_symbol": "AED",
                  "exchange_rate": "4.09500"
                },
                {
                  "id": "ALL",
                  "symbol": "ALL",
                  "html_symbol": "ALL",
                  "exchange_rate": "121.50000"
                }
            ],
            "categories_list": [
                "Auto",
                "Telefono e internet"
            ],
            "payment_accounts_list": [
                {
                  "id": 111,
                  "name": "Indesa - carta conto"
                }
            ],
            "vat_types_list": [
                {
                  "id": 1334,
                  "value": 0,
                  "description": "Non imp. art. 17 c. 6 DPR 633/72 e s.m.i.",
                  "is_disabled": false
                },
                {
                  "id": 1333,
                  "value": 0,
                  "description": "Non sogg. art. 74 c. 7 e 8 DPR 633/72",
                  "is_disabled": false
                }
            ]
        }';

        $this->array = json_decode($json, true);

        $this->object = ObjectSerializer::deserialize($json, '\FattureInCloud\Model\ReceivedDocumentInfo');
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ReceivedDocumentInfo"
     */
    public function testReceivedDocumentInfo()
    {
        $this->assertInstanceOf(\FattureInCloud\Model\ReceivedDocumentInfo::class, $this->object);
    }

    /**
     * Test attribute "default_values"
     */
    public function testPropertyDefaultValues()
    {
        $defaultValues = $this->object->getDefaultValues();
        $this->assertInstanceOf(\FattureInCloud\Model\ReceivedDocumentInfoDefaultValues::class, $defaultValues);
        $this->assertEquals($this->array['default_values']['detailed'], $defaultValues->getDetailed());
    }

    /**
     * Test attribute "items_default_values"
     */
    public function testPropertyItemsDefaultValues()
    {
        $itemsDefaultValues = $this->object->getItemsDefaultValues();
        $this->assertInstanceOf(\FattureInCloud\Model\ReceivedDocumentInfoItemsDefaultValues::class, $itemsDefaultValues);
        $this->assertEquals($this->array['items_default_values']['vat'], $itemsDefaultValues->getVat());
    }

    /**
     * Test attribute "countries_list"
     */
    public function testPropertyCountriesList()
    {
        $this->assertEquals($this->array['countries_list'], $this->object->getCountriesList());
    }

    /**
     * Test attribute "currencies_list"
     */
    public function testPropertyCurrenciesList()
    {
        $currenciesList = $this->object->getCurrenciesList();
        $this->assertIsArray($currenciesList);
        $this->assertCount(2, $currenciesList);
        
        $currency = $currenciesList[0];
        $this->assertInstanceOf(\FattureInCloud\Model\Currency::class, $currency);
        $this->assertEquals($this->array['currencies_list'][0]['id'], $currency->getId());
        $this->assertEquals($this->array['currencies_list'][0]['symbol'], $currency->getSymbol());
    }

    /**
     * Test attribute "categories_list"
     */
    public function testPropertyCategoriesList()
    {
        $this->assertEquals($this->array['categories_list'], $this->object->getCategoriesList());
    }

    /**
     * Test attribute "payment_accounts_list"
     */
    public function testPropertyPaymentAccountsList()
    {
        $paymentAccountsList = $this->object->getPaymentAccountsList();
        $this->assertIsArray($paymentAccountsList);
        $this->assertCount(1, $paymentAccountsList);
        
        $paymentAccount = $paymentAccountsList[0];
        $this->assertInstanceOf(\FattureInCloud\Model\PaymentAccount::class, $paymentAccount);
        $this->assertEquals($this->array['payment_accounts_list'][0]['id'], $paymentAccount->getId());
        $this->assertEquals($this->array['payment_accounts_list'][0]['name'], $paymentAccount->getName());
    }

    /**
     * Test attribute "vat_types_list"
     */
    public function testPropertyVatTypesList()
    {
        $vatTypesList = $this->object->getVatTypesList();
        $this->assertIsArray($vatTypesList);
        $this->assertCount(2, $vatTypesList);
        
        $vatType = $vatTypesList[0];
        $this->assertInstanceOf(\FattureInCloud\Model\VatType::class, $vatType);
        $this->assertEquals($this->array['vat_types_list'][0]['id'], $vatType->getId());
        $this->assertEquals($this->array['vat_types_list'][0]['value'], $vatType->getValue());
        $this->assertEquals($this->array['vat_types_list'][0]['description'], $vatType->getDescription());
    }
}
