<?php

/**
 * WebhooksSubscriptionTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  FattureInCloud
 * @author   Fatture In Cloud API team
 * @link     https://fattureincloud.it
 */

/**
 * Fatture in Cloud API v2 - API Reference
 *
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.27
 * Contact: info@fattureincloud.it
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FattureInCloud\Test\Model;

use PHPUnit\Framework\TestCase;
use \FattureInCloud\ObjectSerializer;

/**
 * WebhooksSubscriptionTest Class Doc Comment
 *
 * @category    Class
 * @description WebhooksSubscription
 * @package     FattureInCloud
 * @author   Fatture In Cloud API team
 * @link     https://fattureincloud.it
 */
class WebhooksSubscriptionTest extends TestCase
{
    public $array = [];
    public $object;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
        $json = '{
            "id": "SUB123",
            "sink": "https://endpoint.test",
            "verified": true,
            "types": ["it.fattureincloud.webhooks.cashbook.create"],
            "config": {
                "mapping": "structured"
            }
        }';

        $this->array = json_decode($json, true);

        $this->object = ObjectSerializer::deserialize($json, '\FattureInCloud\Model\WebhooksSubscription');
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "WebhooksSubscription"
     */
    public function testWebhooksSubscription()
    {
        $this->assertInstanceOf(
            \FattureInCloud\Model\WebhooksSubscription::class,
            $this->object
        );
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        $this->assertEquals($this->array['id'], $this->object->getId());
    }

    /**
     * Test attribute "sink"
     */
    public function testPropertySink()
    {
        $this->assertEquals($this->array['sink'], $this->object->getSink());
    }

    /**
     * Test attribute "verified"
     */
    public function testPropertyVerified()
    {
        $this->assertEquals($this->array['verified'], $this->object->getVerified());
    }

    /**
     * Test attribute "types"
     */
    public function testPropertyTypes()
    {
        $this->assertEquals($this->array['types'], $this->object->getTypes());
    }

    /**
     * Test attribute "config"
     */
    public function testPropertyConfig()
    {
        $configObject = $this->object->getConfig();
        $this->assertInstanceOf(\FattureInCloud\Model\WebhooksSubscriptionConfig::class, $configObject);

        // Verify the config values match the setup data
        $this->assertEquals($this->array['config']['mapping'], $configObject->getMapping());
    }

    /**
     * Test setter for "id"
     */
    public function testSetId()
    {
        $object = new \FattureInCloud\Model\WebhooksSubscription();
        $testValue = 'wh_12345';

        $object->setId($testValue);
        $this->assertEquals($testValue, $object->getId());
    }

    /**
     * Test setter for "sink"
     */
    public function testSetSink()
    {
        $object = new \FattureInCloud\Model\WebhooksSubscription();
        $testValue = 'https://example.com/webhook';

        $object->setSink($testValue);
        $this->assertEquals($testValue, $object->getSink());
    }

    /**
     * Test setter for "verified"
     */
    public function testSetVerified()
    {
        $object = new \FattureInCloud\Model\WebhooksSubscription();
        $testValue = true;

        $object->setVerified($testValue);
        $this->assertEquals($testValue, $object->getVerified());
    }

    /**
     * Test setter for "types"
     */
    public function testSetTypes()
    {
        $object = new \FattureInCloud\Model\WebhooksSubscription();
        $testValue = [];

        $object->setTypes($testValue);
        $this->assertEquals($testValue, $object->getTypes());
    }

    /**
     * Test setter for "config"
     */
    public function testSetConfig()
    {
        $object = new \FattureInCloud\Model\WebhooksSubscription();
        $testValue = new \FattureInCloud\Model\WebhooksSubscriptionConfig();

        $object->setConfig($testValue);
        $this->assertEquals($testValue, $object->getConfig());
    }
}
