name: PHP SDK Validation

on:
  pull_request:
    branches: [ master ]

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:
    - id: checkout
      name: Checkout repo
      uses: actions/checkout@v2

    - id: setup-php
      if: ${{ env.ACT }}
      name: Setup PHP
      run: |
        sudo apt update
        sudo apt install php-cli php-curl php-mbstring php-xml unzip -y
        wget -O composer-setup.php https://getcomposer.org/installer
        sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer

    - id: composer-validation
      name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - id: composer-install
      name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - id: php-unit-tests
      name: Run test suite
      run: ./vendor/bin/phpunit

    - id: psalm-validation
      name: Psalm
      uses: docker://vimeo/psalm-github-actions
      with:
        security_analysis: true
