name: Validate PHP SDK

on:
  pull_request:
    branches: [ master, master-php71 ]

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.1'

    - name: Install composer
      run: |
        wget -O composer-setup.php https://getcomposer.org/installer
        sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer
        php -v

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: ./vendor/bin/phpunit
    
    - id: psalm-validation
      name: Psalm Validation
      run: |
        composer require --dev vimeo/psalm
        ./vendor/bin/psalm --init
        composer require --dev alexeyshockov/guzzle-psalm-plugin && vendor/bin/psalm-plugin enable alexeyshockov/guzzle-psalm-plugin
        ./vendor/bin/psalm
        ./vendor/bin/psalm --taint-analysis 
